# Generated by Django 4.1.7 on 2023-04-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_pedido_lista_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='lista_productos',
            field=models.JSONField(default=list),
        ),
    ]
