# Generated by Django 4.1.7 on 2023-04-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_pedido_lista_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
