# Generated by Django 4.1.7 on 2023-04-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_pedido_costo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='costo_total',
        ),
    ]
